# Generated by Django 4.2.3 on 2023-07-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='class_name',
        ),
        migrations.AddField(
            model_name='registration',
            name='class_field',
            field=models.CharField(default='', max_length=20),
        ),
    ]
